In [605]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\rahs\appdata\local\programs\python\python311\lib\site-packages (2.0.1)

In [606]:
import pandas as pd
# excel file
data1 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='SO2')

In [607]:
data2 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='NOx')
data3 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='PM10')
data4 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='PM2.5')
data5 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='NH3')
data6 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='Ozone')
data7 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='CO')
data8 =  pd.read_excel('D:\ACoding\AQ-Predators\dataset\Air quality\AAQ Data 2016.xls', sheet_name='Benzene')

In [608]:
data1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,TELANGANA STATE POLLUTION CONTROL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Hyderabad Ambient Air Quality Monitoring - Ave...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SO2 in Âµg/m3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
5,NaN,1,"Balanagar , CITD office",4.3,4.6,4.5,4.7,4.5,4.8,4.9,4.8,4.6,5,4.9,5.2,4.733333
6,NaN,2,"Uppal, Modern food Industry, IDA",4.2,4.4,4.5,4.5,4.6,4.7,5,4.8,4.6,5.4,4.9,5.8,4.783333
7,NaN,3,"Jubilee Hills, Police station",4.2,4.4,4.4,4.5,4.5,4.5,4.5,4.5,4.4,4.9,4.6,6.7,4.675
8,NaN,4,"Paradise, HMWS &SB Pump house",4.2,4.4,4.5,4.6,4.6,4.6,4.7,4.8,4.6,5,4.8,5.6,4.7
9,NaN,5,"Charminar, TSRTC bus station",4.2,4.5,4.5,4.6,4.5,4.7,4.8,4.6,4.6,5.1,4.6,5.8,4.708333
10,NaN,6,"Jeedimetla, Industrial Association building",4.3,4.5,4.4,4.6,4.6,4.8,4.8,4.8,4.6,4.9,4.8,8.9,5.0
11,NaN,7,"Buddha Purnima Project office, Tank Bund",4.3,4.2,4.4,4.5,4.7,4.6,4.5,4.4,4.3,4.7,4.7,4.8,4.508333
12,NaN,8,"MGBS, Bus stand",4.3,4.3,4.4,4.6,4.8,4.6,4.7,4.8,4.5,4.7,4.6,4.8,4.591667
13,NaN,9,"Chikkadapally, Lepakshi Emporium",4.2,4.1,4.5,4.5,4.7,5,4.9,4.9,4.5,5,4.7,5.3,4.691667
14,NaN,10,"Langar House, Police Station",4.3,4.4,4.6,4.6,4.7,4.8,4.7,4.7,4.4,4.9,4.7,4.5,4.608333
15,NaN,11,"Madhapur, Shilpa Kalavedika",4.3,4.2,4.3,4.5,4.7,4.9,4.5,4.5,4.3,4.5,4.5,4.7,4.491667
16,NaN,12,"Shameerpet, MRO office",4.3,4.2,4.3,4.5,4.6,4.4,4.5,4.5,4.4,4.3,4.4,4.6,4.416667
17,NaN,13,"Kukatpally, JNTU",4.3,4.2,4.5,4.6,4.6,5.2,5,4.7,4.5,5.1,5,5.6,4.775
18,NaN,14,"Sainikpuri, MRO office",4.3,4.2,4.4,4.3,4.7,5.1,4.5,4.7,4.3,5.2,4.4,4.3,4.533333
19,NaN,15,"Rajendranagar, NG Ranga Agricultural University",4.2,4.1,4.1,4.3,4.5,4.3,4.3,4.3,4.2,4.6,4.2,4.5,4.3
20,NaN,16,"Nacharam, Police station",4.3,4.3,4.5,4.7,4.7,4.9,4.7,5.2,4.6,5.1,4.8,5,4.733333
21,NaN,17,"Abids, Police station",4.3,4.2,4.4,4.6,4.8,4.7,4.7,4.8,4.4,4.8,4.7,5,4.616667
22,NaN,18,"KBRN Park, DFO office",4.2,4.2,4.5,4.3,4.4,4.3,4.3,4.4,4.2,4.6,4.4,4.5,4.358333
23,NaN,19,Sanathnagar,5.29469,4.7,6.3,9.097026,5.062038,5.270953,5,6.195295,6.812404,13.71205,30.47144,10.4,9.026325
24,NaN,20,HCU,13.042545,9.351498,10.7,9.1,7.07936,4.887878,4.6,4.988065,4.771528,11.81311,18.47602,9.8,9.050834
25,NaN,21,Zoopark,11.350935,6.196918,5.420403,6.1,5.070821,NaN,NaN,8.928455,6.854236,6.086657,13.80522,8.8,7.861364
26,NaN,22,Pashamylaram,23.1,12,10.572109,8.858591,5.648909,4.813937,3.7,4.301424,7.906579,21.40628,36.83995,14.1,12.770648
27,NaN,23,KUDA,7,7,6.7,7,8,7,7,6,8,7,7,8,7.141667
28,NaN,24,"Mee-Seva, Warangal",7,7,7.1,7,8,7,7,7,7,7,6,8,7.091667
29,NaN,25,Balasamudram,6.3,4.8,-,5.5,6.3,8,6,5.5,6.8,7.5,8,9,6.7
30,NaN,26,Nakkalagutta,6.8,4.5,-,6.8,6.3,8,7,5,7,7.3,8,8,6.790909
31,NaN,27,Godavarikhani,9,10,8.96,8,9,7,7,7,8,8,7,8,8.08
32,NaN,28,"DIC building, Karimnagar",8,9,7.7,7,5,5,4,6,6,6,7,7,6.475
33,NaN,29,"CER Club, Kothagudem",8,8,7.4,8,7,6,8,5,7,7,6,8,7.116667
34,NaN,30,Jalasouda,6,7,6.1,8,7,5,8,5,8,7,7,8,6.841667
35,NaN,31,Kothur,9,10,7.5,7,8,10,8,9,9,8,9,9,8.625
36,NaN,32,R.C.Puram,6,6,7,5,5,6,5,5,5,6,6,5,5.583333
37,NaN,33,Bollaram,10,Ins. Repair,NaN,NaN,12,14,13,12,14,13,14,10,12.444444
38,NaN,34,Sangareddy,5,5,5,5,5,5,5,5,5,5,5,5,5
39,NaN,35,PETL,13,12,14,13,11,11,12,12,12,12,9,9,11.666667
40,NaN,36,Gaddapotharam,5,5,6,5,5,6,6,5,6,5,5,5,5.333333
41,NaN,37,"Nalgonda RO, Building",7,6,6,5,6,6,6,6,5,6,6,5,5.833333
42,NaN,38,"Choutuppal, Nalgonda",7,7,7,7,7,6,6,6,6,7,6,5,6.416667
43,NaN,39,Subhasnagar/ Nizamabad,-,-,-,-,-,4,4,5,5,6,5,5,4.857143
44,NaN,40,Adilabad/ Mandamarri,-,-,-,-,-,4,4,4,5,5,5,5,4.571429

In [609]:
# drop all values till 3rd row and make 4th row as header
data1 = data1.drop(data.index[0:4])

In [610]:
# drop unamed0 coloum 
data1 = data1.drop(['Unnamed: 0'], axis=1)

In [611]:
# reset index
data1 = data1.reset_index(drop=True)

In [612]:
# set 1st row as header
data1.columns = data1.iloc[0]

In [613]:
# drop 1st row
data1 = data1.drop(data1.index[0])

In [614]:
# reset index
data1 = data1.reset_index(drop=True)

In [615]:
data1

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,"Balanagar , CITD office",4.3,4.6,4.5,4.7,4.5,4.8,4.9,4.8,4.6,5,4.9,5.2,4.733333
1,2,"Uppal, Modern food Industry, IDA",4.2,4.4,4.5,4.5,4.6,4.7,5,4.8,4.6,5.4,4.9,5.8,4.783333
2,3,"Jubilee Hills, Police station",4.2,4.4,4.4,4.5,4.5,4.5,4.5,4.5,4.4,4.9,4.6,6.7,4.675
3,4,"Paradise, HMWS &SB Pump house",4.2,4.4,4.5,4.6,4.6,4.6,4.7,4.8,4.6,5,4.8,5.6,4.7
4,5,"Charminar, TSRTC bus station",4.2,4.5,4.5,4.6,4.5,4.7,4.8,4.6,4.6,5.1,4.6,5.8,4.708333
5,6,"Jeedimetla, Industrial Association building",4.3,4.5,4.4,4.6,4.6,4.8,4.8,4.8,4.6,4.9,4.8,8.9,5.0
6,7,"Buddha Purnima Project office, Tank Bund",4.3,4.2,4.4,4.5,4.7,4.6,4.5,4.4,4.3,4.7,4.7,4.8,4.508333
7,8,"MGBS, Bus stand",4.3,4.3,4.4,4.6,4.8,4.6,4.7,4.8,4.5,4.7,4.6,4.8,4.591667
8,9,"Chikkadapally, Lepakshi Emporium",4.2,4.1,4.5,4.5,4.7,5,4.9,4.9,4.5,5,4.7,5.3,4.691667
9,10,"Langar House, Police Station",4.3,4.4,4.6,4.6,4.7,4.8,4.7,4.7,4.4,4.9,4.7,4.5,4.608333
10,11,"Madhapur, Shilpa Kalavedika",4.3,4.2,4.3,4.5,4.7,4.9,4.5,4.5,4.3,4.5,4.5,4.7,4.491667
11,12,"Shameerpet, MRO office",4.3,4.2,4.3,4.5,4.6,4.4,4.5,4.5,4.4,4.3,4.4,4.6,4.416667
12,13,"Kukatpally, JNTU",4.3,4.2,4.5,4.6,4.6,5.2,5,4.7,4.5,5.1,5,5.6,4.775
13,14,"Sainikpuri, MRO office",4.3,4.2,4.4,4.3,4.7,5.1,4.5,4.7,4.3,5.2,4.4,4.3,4.533333
14,15,"Rajendranagar, NG Ranga Agricultural University",4.2,4.1,4.1,4.3,4.5,4.3,4.3,4.3,4.2,4.6,4.2,4.5,4.3
15,16,"Nacharam, Police station",4.3,4.3,4.5,4.7,4.7,4.9,4.7,5.2,4.6,5.1,4.8,5,4.733333
16,17,"Abids, Police station",4.3,4.2,4.4,4.6,4.8,4.7,4.7,4.8,4.4,4.8,4.7,5,4.616667
17,18,"KBRN Park, DFO office",4.2,4.2,4.5,4.3,4.4,4.3,4.3,4.4,4.2,4.6,4.4,4.5,4.358333
18,19,Sanathnagar,5.29469,4.7,6.3,9.097026,5.062038,5.270953,5,6.195295,6.812404,13.71205,30.47144,10.4,9.026325
19,20,HCU,13.042545,9.351498,10.7,9.1,7.07936,4.887878,4.6,4.988065,4.771528,11.81311,18.47602,9.8,9.050834
20,21,Zoopark,11.350935,6.196918,5.420403,6.1,5.070821,NaN,NaN,8.928455,6.854236,6.086657,13.80522,8.8,7.861364
21,22,Pashamylaram,23.1,12,10.572109,8.858591,5.648909,4.813937,3.7,4.301424,7.906579,21.40628,36.83995,14.1,12.770648
22,23,KUDA,7,7,6.7,7,8,7,7,6,8,7,7,8,7.141667
23,24,"Mee-Seva, Warangal",7,7,7.1,7,8,7,7,7,7,7,6,8,7.091667
24,25,Balasamudram,6.3,4.8,-,5.5,6.3,8,6,5.5,6.8,7.5,8,9,6.7
25,26,Nakkalagutta,6.8,4.5,-,6.8,6.3,8,7,5,7,7.3,8,8,6.790909
26,27,Godavarikhani,9,10,8.96,8,9,7,7,7,8,8,7,8,8.08
27,28,"DIC building, Karimnagar",8,9,7.7,7,5,5,4,6,6,6,7,7,6.475
28,29,"CER Club, Kothagudem",8,8,7.4,8,7,6,8,5,7,7,6,8,7.116667
29,30,Jalasouda,6,7,6.1,8,7,5,8,5,8,7,7,8,6.841667
30,31,Kothur,9,10,7.5,7,8,10,8,9,9,8,9,9,8.625
31,32,R.C.Puram,6,6,7,5,5,6,5,5,5,6,6,5,5.583333
32,33,Bollaram,10,Ins. Repair,NaN,NaN,12,14,13,12,14,13,14,10,12.444444
33,34,Sangareddy,5,5,5,5,5,5,5,5,5,5,5,5,5
34,35,PETL,13,12,14,13,11,11,12,12,12,12,9,9,11.666667
35,36,Gaddapotharam,5,5,6,5,5,6,6,5,6,5,5,5,5.333333
36,37,"Nalgonda RO, Building",7,6,6,5,6,6,6,6,5,6,6,5,5.833333
37,38,"Choutuppal, Nalgonda",7,7,7,7,7,6,6,6,6,7,6,5,6.416667
38,39,Subhasnagar/ Nizamabad,-,-,-,-,-,4,4,5,5,6,5,5,4.857143
39,40,Adilabad/ Mandamarri,-,-,-,-,-,4,4,4,5,5,5,5,4.571429

In [616]:
data2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,TELANGANA STATE POLLUTION CONTROL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Hyderabad Ambient Air Quality Monitoring - Ave...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NOx in Âµg/m3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
5,NaN,1,"Balanagar , CITD office",29.2,26.3,37.7,30.8,27.1,27.9,26.1,25.8,29.2,33,36.7,43.8,31.133333
6,NaN,2,"Uppal, Modern food Industry, IDA",24.7,26,23.8,26.9,26.1,32.7,23.3,25.6,28.9,27.3,32.4,43.7,28.45
7,NaN,3,"Jubilee Hills, Police station",28.7,28.5,30.3,26.8,27.3,26.9,22.7,29.1,29.7,28.6,27.5,31.3,28.116667
8,NaN,4,"Paradise, HMWS &SB Pump house",31.9,25.3,28.2,29.3,28.3,28.5,20.6,30.2,30,26.9,32.1,35.3,28.883333
9,NaN,5,"Charminar, TSRTC bus station",32,30,33.4,33,31.1,28.5,22.3,25.6,27.5,32.5,34.3,34.2,30.366667
10,NaN,6,"Jeedimetla, Industrial Association building",28.6,26.1,26,26.1,29.2,30,22.7,26.9,27.3,28.3,33,31.2,27.95
11,NaN,7,"Buddha Purnima Project office, Tank Bund",17.4,22.1,20.1,20.8,23.3,22.1,20.6,18.1,16.9,21.7,19.6,24.6,20.608333
12,NaN,8,"MGBS, Bus stand",21.3,20.7,19.6,21.5,20.6,20.1,19.6,20.2,18,21.8,23,23.8,20.85
13,NaN,9,"Chikkadapally, Lepakshi Emporium",21.9,21.5,22.9,18.5,21,23.1,25.7,22.2,20.3,25.1,20.9,25.1,22.35
14,NaN,10,"Langar House, Police Station",23.1,21.7,19.9,22.4,26.6,25.1,21.8,21.4,20.7,25.4,22.8,24.4,22.941667
15,NaN,11,"Madhapur, Shilpa Kalavedika",20.6,19.7,19.3,19.1,22.6,18.9,17.8,18,16.7,18.4,17,19.6,18.975
16,NaN,12,"Shameerpet, MRO office",17.7,16.7,16.4,20,19.6,16.5,16.9,15.5,14.9,16.8,15.6,18.6,17.1
17,NaN,13,"Kukatpally, JNTU",22.3,22.3,24,25.2,28,25.9,22.1,23.8,24.6,25.1,33.2,41.1,26.466667
18,NaN,14,"Sainikpuri, MRO office",15.8,18.8,18.3,16.9,17.7,18.9,15.4,17.9,16,19.5,19.7,18.8,17.808333
19,NaN,15,"Rajendranaga, NG Rang Agricultural University",16.1,16.2,16.2,16.6,16.1,16.1,15,16.4,12.9,16.9,14.3,17.2,15.833333
20,NaN,16,"Nacharam, Police station",20.6,22.9,22.3,23.5,24.3,23.6,25,21.2,20.3,26,23.7,25.8,23.266667
21,NaN,17,"Abids, Police station",22.7,26.7,24.5,26.2,25.8,24.3,25,22,20.3,23.8,25.3,23.4,24.166667
22,NaN,18,"KBRN Park, DFO office",19.8,15.7,24,17.2,18.5,17.7,14.9,17.1,14.4,19.6,17.5,20.2,18.05
23,NaN,19,Punjagutta,68.793843,51.098616,66.17,75.157058,71.154023,77.925907,78.5,NaN,NaN,NaN,NaN,-,69.828492
24,NaN,20,Sanathnagar,67.1101,46.2,48.3,51.090372,47.392425,30.45251,25.6,24.03859,25.69912,51.16865,60.38508,45.5,43.578071
25,NaN,21,HCU,59.705381,54.431707,57.4,60,18.854597,11.24652,11.6,29.74674,33.41584,47.63754,65.09923,42.9,41.00313
26,NaN,22,Zoopark,58.755689,57.6,55.813636,49.2,52.419814,NaN,NaN,17.89061,16.50282,42.48441,64.88364,48.6,46.415062
27,NaN,23,Pashamylaram,82.7,62.7,55.01,56.111595,76.297074,65.92497,66.6,75.53783,64.87439,69.47612,44.70104,65.1,65.419418
28,NaN,24,KUDA,20,20,22.8,28,22,20,22,20,25,26,23,30,23.233333
29,NaN,25,"Mee-Seva, Warangal",26,19,21.8,20,19,22,20,28,20,22,22,30,22.483333
30,NaN,26,Balasamudram,9.8,9,-,14,11.5,14,15,9.5,14,18.2,26,28,15.363636
31,NaN,27,Nakkalagutta,10.3,9.5,-,16,14.5,13,17,10,15.8,19.8,29,26,16.445455
32,NaN,28,Godavarikhani,21,26,36,34,30,31,23,25,28,26,29,27,28
33,NaN,29,"DIC building, Karimnagar",22,25,32.1,29,21,19,20,20,23,23,23,26,23.591667
34,NaN,30,"CER Club, Kothagudem",22,20,20.7,21,19,13,24,17,31,24,23,28,21.891667
35,NaN,31,Jalasouda,19,19,20.7,19,19,21,22,14,17,23,24,27,20.391667
36,NaN,32,Kothur,28,32,29.5,26,39,34,35,35,20,31,29,28,30.541667
37,NaN,33,R.C.Puram,28,28,27,26,26,25,26,25,22,26,24,24,25.583333
38,NaN,34,Bollaram,26,Ins. Repair,NaN,NaN,24,26,24,25,24,28,26,26,25.444444
39,NaN,35,Sangareddy,23,23,21,23,23,22,21,22,20,24,22,23,22.25
40,NaN,36,PETL,21,24,25,25,23,21,24,27,23,25,24,25,23.916667
41,NaN,37,Gaddapotharam,27,27,27,27,26,24,25,23,22,23,23,24,24.833333
42,NaN,38,"Nalgonda RO, Building",27,27,26,25,27,26,26,25,24,25,26,23,25.583333
43,NaN,39,"Choutuppal, Nalgonda",28,28,29,28,28,28,27,28,25,27,25,25,27.166667
44,NaN,40,Subhasnagar/ Nizamabad,-,-,-,-,-,15,17,18,18,22,21,21,18.857143
45,NaN,41,Adilabad/ Mandamarri,-,-,-,-,-,15,16,17,18,22,20,21,18.428571

In [617]:
data3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,TELANGANA STATE POLLUTION CONTROL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Hyderabad Ambient Air Quality Monitoring - Ave...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,PM10 in Âµg/m3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,S.NO,Station Name,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
5,NaN,1,"Balanagar , CITD office",184,208,124,136,114,107,96,108,87,105,152,147,130.666667
6,NaN,2,"Uppal, Modern food Industry, IDA",116,105,96,94,87,92,78,67,66,94,120,131,95.5
7,NaN,3,"Jubilee Hills, Police station",111,129,109,113,103,96,81,79,65,106,127,172,107.583333
8,NaN,4,"Paradise, HMWS &SB Pump house",139,146,135,141,129,119,101,105,91,104,120,117,120.583333
9,NaN,5,"Charminar, TSRTC bus station",134,129,109,116,100,99,85,85,71,99,143,124,107.833333
10,NaN,6,"Jeedimetla, Industrial Association building",172,134,133,122,111,93,75,76,73,108,151,134,115.166667
11,NaN,7,Buddha Purnima Project office,77,77,70,52,67,52,41,47,38,57,81,106,63.75
12,NaN,8,"MGBS, Bus stand",81,80,98,95,71,67,68,54,47,74,83,90,75.666667
13,NaN,9,"Chikkadapally, Lepakshi Emporium",90,83,93,74,66,73,63,78,62,89,100,109,81.666667
14,NaN,10,"Langar House, Police Station",120,125,112,86,70,68,65,64,54,75,109,116,88.666667
15,NaN,11,"Madhapur, Shilpa Kalavedika",97,90,89,84,70,58,55,49,40,65,101,105,75.25
16,NaN,12,"Shameerpet, MRO office",82,64,84,78,62,77,65,75,71,74,83,60,72.916667
17,NaN,13,"Kukatpally, JNTU",99,83,78,84,80,80,67,65,65,95,137,139,89.333333
18,NaN,14,"Sainikpuri, MRO office",85,88,85,71,78,79,66,73,62,91,80,114,81
19,NaN,15,"Rajendranaga, NG Rang Agricultural University",63,76,67,72,65,64,71,60,58,66,75,78,67.916667
20,NaN,16,"Nacharam, Police station",129,136,131,128,112,104,98,68,60,106,132,139,111.916667
21,NaN,17,"Abids, Police station",136,121,118,122,91,79,87,77,70,105,136,140,106.833333
22,NaN,18,"KBRN Park, DFO office",80,67,78,64,45,41,36,39,30,54,87,76,58.083333
23,NaN,19,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,NaN,NaN,NaN,NaN,-,111.460011
24,NaN,20,HCU,102.967742,90.965517,106,92,58.551724,36,28,31.3566,33.10981,94.40902,142.6903,80.3,74.695893
25,NaN,21,Zoopark,165.240592,130.689655,131.612903,115,81.184277,NaN,NaN,38.27944,35.21622,115.4603,176.5938,117,110.627719
26,NaN,22,Pashamylaram,104.7,92.057818,105.166667,92.794441,63.651302,49.49132,37,43.81779,62.67391,132.7546,194.0749,96,89.515229
27,NaN,23,KUDA,73,72,68,74,76,72,51,44,46,62,56,83,64.75
28,NaN,24,"Mee-Seva, Warangal",76,72,63,73,84,68,56,36,52,61,83,84,67.333333
29,NaN,25,Balasamudram,56,51,-,62,76,70,64,58,53,52,88,87,65.181818
30,NaN,26,Nakkalagutta,66,65,-,77,83,67,57,60,57,71,76,81,69.090909
31,NaN,27,Godavarikhani,115,93,76,74,56,41,23,41,35,58,98,106,68
32,NaN,28,"DIC building, Karimnagar",69,59,42,62,52,47,23,33,29,50,69,83,51.5
33,NaN,29,"CER Club, Kothagudem",77,71,61,63,60,49,37,45,47,60,56,66,57.666667
34,NaN,30,Jalasouda,46,51,54,51,47,47,41,37,39,48,55,60,48
35,NaN,31,Kothur,98,82,71,95,61,77,61,73,52,86,96,70,76.833333
36,NaN,32,R.C.Puram,98,97,93,91,61,56,48,56,47,84,97,91,76.583333
37,NaN,33,Bollaram,171,Ins. Repair,NaN,NaN,165,200,190,108,111,134,136,148,151.444444
38,NaN,34,Sangareddy,79,70,75,66,61,56,50,58,46,76,79,75,65.916667
39,NaN,35,PETL,97,95,97,79,70,86,74,92,60,72,84,89,82.916667
40,NaN,36,Gaddapotharam,97,95,90,82,58,50,44,58,42,75,88,79,71.5
41,NaN,37,"Nalgonda RO, Building",64,62,59,61,54,55,54,54,56,59,58,65,58.416667
42,NaN,38,"Choutuppal, Nalgonda",49,66,74,69,69,59,61,57,60,63,61,61,62.416667
43,NaN,39,Subhasnagar/ Nizamabad,67,64,66,68,71,61,57,58,56,64,60,62,62.833333
44,NaN,40,Adilabad/ Mandamarri,62,68,71,70,69,66,60,61,58,67,63,65,65

In [618]:
# drop 1st 3 rows
data2 = data2.drop(data2.index[0:4])
data3 = data3.drop(data3.index[0:4])

In [619]:
# drop unamed0 coloum
data2 = data2.drop(['Unnamed: 0'], axis=1)
data3 = data3.drop(['Unnamed: 0'], axis=1)

In [620]:
data2 = data2.reset_index(drop=True)
data3 = data3.reset_index(drop=True)

In [621]:
# set 1st row as header
data2.columns = data2.iloc[0]
data3.columns = data3.iloc[0]

In [622]:
# drop 1st row
data2 = data2.drop(data2.index[0])
data3 = data3.drop(data3.index[0])

In [623]:
# reset index
data2 = data2.reset_index(drop=True)
data3 = data3.reset_index(drop=True)

In [624]:
data2

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,"Balanagar , CITD office",29.2,26.3,37.7,30.8,27.1,27.9,26.1,25.8,29.2,33,36.7,43.8,31.133333
1,2,"Uppal, Modern food Industry, IDA",24.7,26,23.8,26.9,26.1,32.7,23.3,25.6,28.9,27.3,32.4,43.7,28.45
2,3,"Jubilee Hills, Police station",28.7,28.5,30.3,26.8,27.3,26.9,22.7,29.1,29.7,28.6,27.5,31.3,28.116667
3,4,"Paradise, HMWS &SB Pump house",31.9,25.3,28.2,29.3,28.3,28.5,20.6,30.2,30,26.9,32.1,35.3,28.883333
4,5,"Charminar, TSRTC bus station",32,30,33.4,33,31.1,28.5,22.3,25.6,27.5,32.5,34.3,34.2,30.366667
5,6,"Jeedimetla, Industrial Association building",28.6,26.1,26,26.1,29.2,30,22.7,26.9,27.3,28.3,33,31.2,27.95
6,7,"Buddha Purnima Project office, Tank Bund",17.4,22.1,20.1,20.8,23.3,22.1,20.6,18.1,16.9,21.7,19.6,24.6,20.608333
7,8,"MGBS, Bus stand",21.3,20.7,19.6,21.5,20.6,20.1,19.6,20.2,18,21.8,23,23.8,20.85
8,9,"Chikkadapally, Lepakshi Emporium",21.9,21.5,22.9,18.5,21,23.1,25.7,22.2,20.3,25.1,20.9,25.1,22.35
9,10,"Langar House, Police Station",23.1,21.7,19.9,22.4,26.6,25.1,21.8,21.4,20.7,25.4,22.8,24.4,22.941667
10,11,"Madhapur, Shilpa Kalavedika",20.6,19.7,19.3,19.1,22.6,18.9,17.8,18,16.7,18.4,17,19.6,18.975
11,12,"Shameerpet, MRO office",17.7,16.7,16.4,20,19.6,16.5,16.9,15.5,14.9,16.8,15.6,18.6,17.1
12,13,"Kukatpally, JNTU",22.3,22.3,24,25.2,28,25.9,22.1,23.8,24.6,25.1,33.2,41.1,26.466667
13,14,"Sainikpuri, MRO office",15.8,18.8,18.3,16.9,17.7,18.9,15.4,17.9,16,19.5,19.7,18.8,17.808333
14,15,"Rajendranaga, NG Rang Agricultural University",16.1,16.2,16.2,16.6,16.1,16.1,15,16.4,12.9,16.9,14.3,17.2,15.833333
15,16,"Nacharam, Police station",20.6,22.9,22.3,23.5,24.3,23.6,25,21.2,20.3,26,23.7,25.8,23.266667
16,17,"Abids, Police station",22.7,26.7,24.5,26.2,25.8,24.3,25,22,20.3,23.8,25.3,23.4,24.166667
17,18,"KBRN Park, DFO office",19.8,15.7,24,17.2,18.5,17.7,14.9,17.1,14.4,19.6,17.5,20.2,18.05
18,19,Punjagutta,68.793843,51.098616,66.17,75.157058,71.154023,77.925907,78.5,NaN,NaN,NaN,NaN,-,69.828492
19,20,Sanathnagar,67.1101,46.2,48.3,51.090372,47.392425,30.45251,25.6,24.03859,25.69912,51.16865,60.38508,45.5,43.578071
20,21,HCU,59.705381,54.431707,57.4,60,18.854597,11.24652,11.6,29.74674,33.41584,47.63754,65.09923,42.9,41.00313
21,22,Zoopark,58.755689,57.6,55.813636,49.2,52.419814,NaN,NaN,17.89061,16.50282,42.48441,64.88364,48.6,46.415062
22,23,Pashamylaram,82.7,62.7,55.01,56.111595,76.297074,65.92497,66.6,75.53783,64.87439,69.47612,44.70104,65.1,65.419418
23,24,KUDA,20,20,22.8,28,22,20,22,20,25,26,23,30,23.233333
24,25,"Mee-Seva, Warangal",26,19,21.8,20,19,22,20,28,20,22,22,30,22.483333
25,26,Balasamudram,9.8,9,-,14,11.5,14,15,9.5,14,18.2,26,28,15.363636
26,27,Nakkalagutta,10.3,9.5,-,16,14.5,13,17,10,15.8,19.8,29,26,16.445455
27,28,Godavarikhani,21,26,36,34,30,31,23,25,28,26,29,27,28
28,29,"DIC building, Karimnagar",22,25,32.1,29,21,19,20,20,23,23,23,26,23.591667
29,30,"CER Club, Kothagudem",22,20,20.7,21,19,13,24,17,31,24,23,28,21.891667
30,31,Jalasouda,19,19,20.7,19,19,21,22,14,17,23,24,27,20.391667
31,32,Kothur,28,32,29.5,26,39,34,35,35,20,31,29,28,30.541667
32,33,R.C.Puram,28,28,27,26,26,25,26,25,22,26,24,24,25.583333
33,34,Bollaram,26,Ins. Repair,NaN,NaN,24,26,24,25,24,28,26,26,25.444444
34,35,Sangareddy,23,23,21,23,23,22,21,22,20,24,22,23,22.25
35,36,PETL,21,24,25,25,23,21,24,27,23,25,24,25,23.916667
36,37,Gaddapotharam,27,27,27,27,26,24,25,23,22,23,23,24,24.833333
37,38,"Nalgonda RO, Building",27,27,26,25,27,26,26,25,24,25,26,23,25.583333
38,39,"Choutuppal, Nalgonda",28,28,29,28,28,28,27,28,25,27,25,25,27.166667
39,40,Subhasnagar/ Nizamabad,-,-,-,-,-,15,17,18,18,22,21,21,18.857143
40,41,Adilabad/ Mandamarri,-,-,-,-,-,15,16,17,18,22,20,21,18.428571

In [625]:
data3

,S.NO,Station Name,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,"Balanagar , CITD office",184,208,124,136,114,107,96,108,87,105,152,147,130.666667
1,2,"Uppal, Modern food Industry, IDA",116,105,96,94,87,92,78,67,66,94,120,131,95.5
2,3,"Jubilee Hills, Police station",111,129,109,113,103,96,81,79,65,106,127,172,107.583333
3,4,"Paradise, HMWS &SB Pump house",139,146,135,141,129,119,101,105,91,104,120,117,120.583333
4,5,"Charminar, TSRTC bus station",134,129,109,116,100,99,85,85,71,99,143,124,107.833333
5,6,"Jeedimetla, Industrial Association building",172,134,133,122,111,93,75,76,73,108,151,134,115.166667
6,7,Buddha Purnima Project office,77,77,70,52,67,52,41,47,38,57,81,106,63.75
7,8,"MGBS, Bus stand",81,80,98,95,71,67,68,54,47,74,83,90,75.666667
8,9,"Chikkadapally, Lepakshi Emporium",90,83,93,74,66,73,63,78,62,89,100,109,81.666667
9,10,"Langar House, Police Station",120,125,112,86,70,68,65,64,54,75,109,116,88.666667
10,11,"Madhapur, Shilpa Kalavedika",97,90,89,84,70,58,55,49,40,65,101,105,75.25
11,12,"Shameerpet, MRO office",82,64,84,78,62,77,65,75,71,74,83,60,72.916667
12,13,"Kukatpally, JNTU",99,83,78,84,80,80,67,65,65,95,137,139,89.333333
13,14,"Sainikpuri, MRO office",85,88,85,71,78,79,66,73,62,91,80,114,81
14,15,"Rajendranaga, NG Rang Agricultural University",63,76,67,72,65,64,71,60,58,66,75,78,67.916667
15,16,"Nacharam, Police station",129,136,131,128,112,104,98,68,60,106,132,139,111.916667
16,17,"Abids, Police station",136,121,118,122,91,79,87,77,70,105,136,140,106.833333
17,18,"KBRN Park, DFO office",80,67,78,64,45,41,36,39,30,54,87,76,58.083333
18,19,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,NaN,NaN,NaN,NaN,-,111.460011
19,20,HCU,102.967742,90.965517,106,92,58.551724,36,28,31.3566,33.10981,94.40902,142.6903,80.3,74.695893
20,21,Zoopark,165.240592,130.689655,131.612903,115,81.184277,NaN,NaN,38.27944,35.21622,115.4603,176.5938,117,110.627719
21,22,Pashamylaram,104.7,92.057818,105.166667,92.794441,63.651302,49.49132,37,43.81779,62.67391,132.7546,194.0749,96,89.515229
22,23,KUDA,73,72,68,74,76,72,51,44,46,62,56,83,64.75
23,24,"Mee-Seva, Warangal",76,72,63,73,84,68,56,36,52,61,83,84,67.333333
24,25,Balasamudram,56,51,-,62,76,70,64,58,53,52,88,87,65.181818
25,26,Nakkalagutta,66,65,-,77,83,67,57,60,57,71,76,81,69.090909
26,27,Godavarikhani,115,93,76,74,56,41,23,41,35,58,98,106,68
27,28,"DIC building, Karimnagar",69,59,42,62,52,47,23,33,29,50,69,83,51.5
28,29,"CER Club, Kothagudem",77,71,61,63,60,49,37,45,47,60,56,66,57.666667
29,30,Jalasouda,46,51,54,51,47,47,41,37,39,48,55,60,48
30,31,Kothur,98,82,71,95,61,77,61,73,52,86,96,70,76.833333
31,32,R.C.Puram,98,97,93,91,61,56,48,56,47,84,97,91,76.583333
32,33,Bollaram,171,Ins. Repair,NaN,NaN,165,200,190,108,111,134,136,148,151.444444
33,34,Sangareddy,79,70,75,66,61,56,50,58,46,76,79,75,65.916667
34,35,PETL,97,95,97,79,70,86,74,92,60,72,84,89,82.916667
35,36,Gaddapotharam,97,95,90,82,58,50,44,58,42,75,88,79,71.5
36,37,"Nalgonda RO, Building",64,62,59,61,54,55,54,54,56,59,58,65,58.416667
37,38,"Choutuppal, Nalgonda",49,66,74,69,69,59,61,57,60,63,61,61,62.416667
38,39,Subhasnagar/ Nizamabad,67,64,66,68,71,61,57,58,56,64,60,62,62.833333
39,40,Adilabad/ Mandamarri,62,68,71,70,69,66,60,61,58,67,63,65,65

In [626]:
data4

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,TELANGANA STATE POLLUTION CONTROL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,PM2.5 in Âµg/m3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-15 00:00:00,2016-05-15 00:00:00,2016-06-15 00:00:00,2016-07-15 00:00:00,2016-08-15 00:00:00,2016-09-15 00:00:00,2016-10-15 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
4,NaN,1,"Balanagar , CITD office",-,-,-,-,33,49,46,43,35,43,75,71,49.375
5,NaN,2,"Uppal, Modern food Industry, IDA",-,-,-,-,32,38,35,28,29,45,60,70,42.125
6,NaN,3,"Jubilee Hills, Police station",-,-,-,-,37,37,34,33,27,37,45,69,39.875
7,NaN,4,"Paradise, HMWS &SB Pump house",-,-,-,-,48,42,50,48,37,50,58,73,50.75
8,NaN,5,"Charminar, TSRTC bus station",-,-,-,-,43,45,39,35,29,46,70,75,47.75
9,NaN,6,"Jeedimetla, Industrial Association Office",-,-,-,-,44,48,37,34,32,49,73,64,47.625
10,NaN,7,Sanathnagar,72.22408,53,61,50.857143,40.135753,29.68814,18,10.29435,19.08601,44.68506,72.96806,46.6,43.21155
11,NaN,8,HCU,49.451613,40.241379,41,33,21.566667,15,10,10.85432,15.01611,43.41203,76.64773,35.9,32.674154
12,NaN,9,Zoopark,79.149194,62.241379,59.354839,48,32,NaN,NaN,17.91037,16.81935,59.96438,103.6406,58.5,53.758011
13,NaN,10,Pashamylaram,54.1,45,43.6,34.099797,22.998591,17.74306,12,12.43079,23.22283,55.8727,101.9308,43.2,38.849881
14,NaN,11,R.C.Puram,-,-,-,-,33,34,15,28,23,28,43,33,29.625
15,NaN,12,Sangareddy,-,-,-,-,36,23,24,13,14,23,36,31,25
16,NaN,13,Gaddapotharam,-,-,-,-,35,24,23,24,19,34,41,34,29.25
17,NaN,14,"Nalgonda RO, Building",-,-,-,-,-,-,-,-,-,-,-,35,35
18,NaN,15,Subhasnagar/ Nizamabad,-,-,-,-,43,38,28,28,27,32,29,32,32.125
19,NaN,16,Adilabad/ Mandamarri,-,-,-,-,40,40,30,29,28,33,30,34,33

In [627]:
data4= data4.drop(data4.index[0:3])

In [628]:
data4 = data4.drop(['Unnamed: 0'], axis=1)

In [629]:
data4 = data4.reset_index(drop=True)

In [630]:
data4.columns = data4.iloc[0]

In [631]:
data4 = data4.drop(data4.index[0])

In [632]:
data4

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-15 00:00:00,2016-05-15 00:00:00,2016-06-15 00:00:00,2016-07-15 00:00:00,2016-08-15 00:00:00,2016-09-15 00:00:00,2016-10-15 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
1,1,"Balanagar , CITD office",-,-,-,-,33,49,46,43,35,43,75,71,49.375
2,2,"Uppal, Modern food Industry, IDA",-,-,-,-,32,38,35,28,29,45,60,70,42.125
3,3,"Jubilee Hills, Police station",-,-,-,-,37,37,34,33,27,37,45,69,39.875
4,4,"Paradise, HMWS &SB Pump house",-,-,-,-,48,42,50,48,37,50,58,73,50.75
5,5,"Charminar, TSRTC bus station",-,-,-,-,43,45,39,35,29,46,70,75,47.75
6,6,"Jeedimetla, Industrial Association Office",-,-,-,-,44,48,37,34,32,49,73,64,47.625
7,7,Sanathnagar,72.22408,53,61,50.857143,40.135753,29.68814,18,10.29435,19.08601,44.68506,72.96806,46.6,43.21155
8,8,HCU,49.451613,40.241379,41,33,21.566667,15,10,10.85432,15.01611,43.41203,76.64773,35.9,32.674154
9,9,Zoopark,79.149194,62.241379,59.354839,48,32,NaN,NaN,17.91037,16.81935,59.96438,103.6406,58.5,53.758011
10,10,Pashamylaram,54.1,45,43.6,34.099797,22.998591,17.74306,12,12.43079,23.22283,55.8727,101.9308,43.2,38.849881
11,11,R.C.Puram,-,-,-,-,33,34,15,28,23,28,43,33,29.625
12,12,Sangareddy,-,-,-,-,36,23,24,13,14,23,36,31,25
13,13,Gaddapotharam,-,-,-,-,35,24,23,24,19,34,41,34,29.25
14,14,"Nalgonda RO, Building",-,-,-,-,-,-,-,-,-,-,-,35,35
15,15,Subhasnagar/ Nizamabad,-,-,-,-,43,38,28,28,27,32,29,32,32.125
16,16,Adilabad/ Mandamarri,-,-,-,-,40,40,30,29,28,33,30,34,33

In [633]:
data5 = data5.drop(data5.index[0:3])

In [634]:
# drop unamed0 coloum
data5 = data5.drop(['Unnamed: 0'], axis=1)

In [635]:
data5 = data5.reset_index(drop=True)

In [636]:
data5.columns = data5.iloc[0]

In [637]:
# drop 1st row
data5 = data5.drop(data5.index[0])

In [638]:
# reset index
data5 = data5.reset_index(drop=True)

In [639]:
data5

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,"Balanagar , CITD office",57,71,88,82,79,79,63,67,97,65,71,83,75.166667
1,2,"Uppal, Modern food Industry, IDA",58,64,85,90,94,122,55,63,77,71,70,75,77
2,3,"Jubilee Hills, Police station",76,79,84,85,82,87,73,79,56,65,60,73,74.916667
3,4,"Paradise, HMWS &SB Pump house",61,47,61,75,75,75,72,75,87,65,65,71,69.083333
4,5,"Charminar, TSRTC bus station",75,105,83,83,105,88,73,70,64,87,63,72,80.666667
5,6,"Jeedimetla, Industrial Association building",149,261,148,102,123,94,67,70,95,103,79,98,115.75
6,7,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,-,-,-,-,-,111.460011
7,8,HCU,20.524323,19.33253,18,20,13.969799,10.88833,8.9,14.47275,12.20577,13.97383,25.14931,17.1,16.20972
8,9,Zoopark,10.458198,10.42952,10.351596,24.5,30.907149,NaN,NaN,16.53539,9.616372,15.59165,20.3662,16.8,16.555608
9,10,Pashamylaram,43.8,29.8,18.401793,15.833707,28.34395,11.94547,13,10.4171,17.6016,24.6967,23.27017,22,21.592541
10,11,KUDA,22,21,22,21,21,21,18,20,20,22,22,22,21
11,12,"Mee-Seva, Warangal",22,21,24,21,21,28,24,22,20,22,21,23,22.416667
12,13,Godavarikhani,31,29,25,25,22,23,18,21,21,21,25,22,23.583333
13,14,"DIC building, Karimnagar",27,24,25,21,23,21,23,21,21,25,22,24,23.083333
14,15,"CER Club, Kothagudem",-,-,-,-,-,20,21,21,21,21,26,21,21.571429
15,16,Jalasouda,-,-,-,-,-,20,22,20,21,21,28,22,22
16,17,Kothur,36,24,28,21,25,47,46,30,29,27,28,24,30.416667
17,18,R.C.Puram,21,21,21,21,21,21,21,21,21,21,21,21,21
18,19,Sangareddy,-,-,-,-,-,21,21,21,21,21,21,21,21
19,20,Gaddapotharam,-,-,-,-,-,22,21,21,21,21,21,21,21.142857
20,21,"Nalgonda RO, Building",21.3,21.2,21.9,21,20,21,21,21,21,21,21,21,21.033333
21,22,"Choutuppal, Nalgonda",27.7,26.7,26.3,27,24,25,23,23,23,22,22,21,24.225
22,23,Subhasnagar/ Nizamabad,-,-,-,-,-,21,21,21,21,21,21,21,21
23,24,Adilabad/ Mandamarri,-,-,-,-,-,21,21,21,21,21,21,21,21

In [640]:
data6 = data6.drop(data6.index[0:5])

In [641]:
data6

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
5,NaN,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
6,NaN,1,Punjagutta,5.814413,2.551924,4.41,3.773212,7.416257,11.224644,6.8,-,-,-,-,-,5.998636
7,NaN,2,HCU,27.070968,23.044828,29,32.4,25.58,24.8,10.2,12.27337,22.06474,35.47315,45.04376,34.9,26.820901
8,NaN,3,Zoopark,32.190325,38.9,44.338514,44.3,36.641379,NaN,NaN,10.3,20.9,31.3,39.4,28.6,32.687022
9,NaN,4,Sanathnagar,78.83308,73.3,76.6,73.324666,57.022625,41.3,21,20.8,25.9,52.4,83.1,67.6,55.931698
10,NaN,5,Pashamylaram,43.6,55.7,56.19557,52.932704,37.888175,6.156533,6.6,15.48519,19.21792,30.22503,56.72544,44.4,35.427213

In [642]:
data6 = data6.drop(['Unnamed: 0'], axis=1)

In [643]:
# reset index
data6 = data6.reset_index(drop=True)

In [644]:
data6.columns = data6.iloc[0]

In [645]:
# drop 1st row
data6 = data6.drop(data6.index[0])
data6 = data6.reset_index(drop=True)

In [646]:
data6

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,Punjagutta,5.814413,2.551924,4.41,3.773212,7.416257,11.224644,6.8,-,-,-,-,-,5.998636
1,2,HCU,27.070968,23.044828,29,32.4,25.58,24.8,10.2,12.27337,22.06474,35.47315,45.04376,34.9,26.820901
2,3,Zoopark,32.190325,38.9,44.338514,44.3,36.641379,NaN,NaN,10.3,20.9,31.3,39.4,28.6,32.687022
3,4,Sanathnagar,78.83308,73.3,76.6,73.324666,57.022625,41.3,21,20.8,25.9,52.4,83.1,67.6,55.931698
4,5,Pashamylaram,43.6,55.7,56.19557,52.932704,37.888175,6.156533,6.6,15.48519,19.21792,30.22503,56.72544,44.4,35.427213

In [647]:
data7 = data7.drop(data7.index[0:5])
data7 = data7.drop(['Unnamed: 0'], axis=1)
data7 = data7.reset_index(drop=True)
data7.columns = data7.iloc[0]
data7 = data7.drop(data7.index[0])
data7 = data7.reset_index(drop=True)

In [648]:
data7

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,Punjagutta,1.900873,1.579276,1.54,1.818254,1.665658,1.680787,1.6,-,-,-,-,-,1.68355
1,2,HCU,0.914516,0.96069,1.04,1,0.878333,0.8,0.7,0.751629,0.835901,0.950597,0.631969,0.8,0.855303
2,3,Zoopark,1.143265,1.052414,0.998393,0.91,0.744483,No data,No data,0.47,0.46,0.71,0.95,1.1,0.853855
3,4,Sanathnagar,0.87413,0.715385,0.76,0.788929,0.712581,0.44,0.45,0.4,0.48,0.63,0.75,0.9,0.658419
4,5,Pashamylaram,1.493887,1.424343,0.709527,0.637408,0.509185,0.530889,0.7,0.835825,0.68689,0.877528,0.938498,1,0.861998

In [649]:
data8=  data8.drop(data8.index[0:5])
data8 = data8.drop(['Unnamed: 0'], axis=1)
data8 = data8.reset_index(drop=True)
data8.columns = data8.iloc[0]
data8 = data8.drop(data8.index[0])
data8 = data8.reset_index(drop=True)

In [650]:
data8

,S.NO,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,1,Punjagutta,0.122069,0.002184,0,2.325061,4.084635,7.796788,5.9,-,-,-,-,-,2.890105
1,2,HCU,0.788733,0.43944,0.5,0.4,0.235452,0.142691,0.1,0.124278,0.214251,0.375652,0.51512,0.4,0.352968
2,3,Zoopark,4.751028,1.6,1.652976,1.1,0.398069,-,-,1.3,0.60803,0.86753,1.289749,1.4,1.496738
3,4,Sanathnagar,2.372242,1.2,1.1,1.125023,0.636786,0.56106,0.5,0.459524,0.651359,0.930611,0.813291,0.7,0.920825
4,5,Pashamylaram,0.507959,0.412609,0.135862,0.427885,0.174628,0.114002,0.1,0.073921,0.171315,0.250188,0.126812,0.1,0.216265

In [651]:
# ignore the S.No. column in each dataframe and merge theme using Sampling Location
data1 = data1.iloc[:, 1:]
data2 = data2.iloc[:, 1:]
data3 = data3.iloc[:, 1:]
data4 = data4.iloc[:, 1:]
data5 = data5.iloc[:, 1:]
data6 = data6.iloc[:, 1:]
data7 = data7.iloc[:, 1:]
data8 = data8.iloc[:, 1:]

In [652]:
data.to_csv('AAQ Data 2016.csv')

In [653]:
# concatinate with sub headers as SO2 NOx PM10 PM2.5 NH3 Ozone CO Benzene
data = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8], axis=1, keys=['SO2', 'NOx', 'PM10', 'PM2.5', 'NH3', 'Ozone', 'CO', 'Benzene'])

In [654]:
data

                                                 SO2                      \
0                                  Sampling Location 2016-01-15 00:00:00
0                           Balanagar , CITD office                  4.3
1                   Uppal, Modern food Industry, IDA                 4.2
2                      Jubilee Hills, Police station                 4.2
3                     Paradise, HMWS &SB Pump house                  4.2
4                      Charminar, TSRTC bus station                  4.2
5        Jeedimetla, Industrial Association building                 4.3
6           Buddha Purnima Project office, Tank Bund                 4.3
7                                   MGBS, Bus stand                  4.3
8                  Chikkadapally, Lepakshi Emporium                  4.2
9                      Langar House, Police Station                  4.3
10                      Madhapur, Shilpa Kalavedika                  4.3
11                            Shameerpet, MRO office                 4.3
12                                  Kukatpally, JNTU                 4.3
13                          Sainikpuri,  MRO office                  4.3
14  Rajendranagar, NG Ranga Agricultural University                  4.2
15                         Nacharam, Police station                  4.3
16                            Abids, Police station                  4.3
17                            KBRN Park, DFO office                  4.2
18                                       Sanathnagar             5.29469
19                                               HCU           13.042545
20                                           Zoopark           11.350935
21                                      Pashamylaram                23.1
22                                              KUDA                   7
23                               Mee-Seva, Warangal                    7
24                                      Balasamudram                 6.3
25                                      Nakkalagutta                 6.8
26                                     Godavarikhani                   9
27                          DIC building, Karimnagar                   8
28                              CER Club, Kothagudem                   8
29                                        Jalasouda                    6
30                                            Kothur                   9
31                                         R.C.Puram                   6
32                                          Bollaram                  10
33                                        Sangareddy                   5
34                                              PETL                  13
35                                     Gaddapotharam                   5
36                             Nalgonda RO, Building                   7
37                              Choutuppal, Nalgonda                   7
38                           Subhasnagar/  Nizamabad                   -
39                              Adilabad/ Mandamarri                   -
40                                               NaN                 NaN

                                                                \
0  2016-02-15 00:00:00 2016-03-15 00:00:00 2016-04-01 00:00:00
0                  4.6                 4.5                 4.7
1                  4.4                 4.5                 4.5
2                  4.4                 4.4                 4.5
3                  4.4                 4.5                 4.6
4                  4.5                 4.5                 4.6
5                  4.5                 4.4                 4.6
6                  4.2                 4.4                 4.5
7                  4.3                 4.4                 4.6
8                  4.1                 4.5                 4.5
9                  4.4                 4.6                 4.6
10                 4.2                 4.3                 4.5
11                 4.2                 4.3                 4.5
12                 4.2                 4.5                 4.6
13                 4.2                 4.4                 4.3
14                 4.1                 4.1                 4.3
15                 4.3                 4.5                 4.7
16                 4.2                 4.4                 4.6
17                 4.2                 4.5                 4.3
18                 4.7                 6.3            9.097026
19            9.351498                10.7                 9.1
20            6.196918            5.420403                 6.1
21                  12           10.572109            8.858591
22                   7                 6.7                   7
23                   7                 7.1                   7
24                 4.8                   -                 5.5
25                 4.5                   -                 6.8
26                  10                8.96                   8
27                   9                 7.7                   7
28                   8                 7.4                   8
29                   7                 6.1                   8
30                  10                 7.5                   7
31                   6                   7                   5
32         Ins. Repair                 NaN                 NaN
33                   5                   5                   5
34                  12                  14                  13
35                   5                   6                   5
36                   6                   6                   5
37                   7                   7                   7
38                   -                   -                   -
39                   -                   -                   -
40                 NaN                 NaN                 NaN

                                                                \
0  2016-05-01 00:00:00 2016-06-01 00:00:00 2016-07-01 00:00:00
0                  4.5                 4.8                 4.9
1                  4.6                 4.7                   5
2                  4.5                 4.5                 4.5
3                  4.6                 4.6                 4.7
4                  4.5                 4.7                 4.8
5                  4.6                 4.8                 4.8
6                  4.7                 4.6                 4.5
7                  4.8                 4.6                 4.7
8                  4.7                   5                 4.9
9                  4.7                 4.8                 4.7
10                 4.7                 4.9                 4.5
11                 4.6                 4.4                 4.5
12                 4.6                 5.2                   5
13                 4.7                 5.1                 4.5
14                 4.5                 4.3                 4.3
15                 4.7                 4.9                 4.7
16                 4.8                 4.7                 4.7
17                 4.4                 4.3                 4.3
18            5.062038            5.270953                   5
19             7.07936            4.887878                 4.6
20            5.070821                 NaN                 NaN
21            5.648909            4.813937                 3.7
22                   8                   7                   7
23                   8                   7                   7
24                 6.3                   8                   6
25                 6.3                   8                   7
26                   9                   7                   7
27                   5                   5                   4
28                   7                   6                   8
29                   7                   5                   8
30                   8                  10                   8
31                   5                   6                   5
32                  12                  14                  13
33                   5                   5                   5
34                  11                  11                  12
35                   5                   6                   6
36                   6                   6                   6
37                   7                   6                   6
38                   -                   4                   4
39                   -                   4                   4
40                 NaN                 NaN                 NaN

                                            ...             Benzene  \
0  2016-08-01 00:00:00 2016-09-01 00:00:00  ... 2016-04-01 00:00:00
0                  4.8                 4.6  ...            2.325061
1                  4.8                 4.6  ...                 0.4
2                  4.5                 4.4  ...                 1.1
3                  4.8                 4.6  ...            1.125023
4                  4.6                 4.6  ...            0.427885
5                  4.8                 4.6  ...                 NaN
6                  4.4                 4.3  ...                 NaN
7                  4.8                 4.5  ...                 NaN
8                  4.9                 4.5  ...                 NaN
9                  4.7                 4.4  ...                 NaN
10                 4.5                 4.3  ...                 NaN
11                 4.5                 4.4  ...                 NaN
12                 4.7                 4.5  ...                 NaN
13                 4.7                 4.3  ...                 NaN
14                 4.3                 4.2  ...                 NaN
15                 5.2                 4.6  ...                 NaN
16                 4.8                 4.4  ...                 NaN
17                 4.4                 4.2  ...                 NaN
18            6.195295            6.812404  ...                 NaN
19            4.988065            4.771528  ...                 NaN
20            8.928455            6.854236  ...                 NaN
21            4.301424            7.906579  ...                 NaN
22                   6                   8  ...                 NaN
23                   7                   7  ...                 NaN
24                 5.5                 6.8  ...                 NaN
25                   5                   7  ...                 NaN
26                   7                   8  ...                 NaN
27                   6                   6  ...                 NaN
28                   5                   7  ...                 NaN
29                   5                   8  ...                 NaN
30                   9                   9  ...                 NaN
31                   5                   5  ...                 NaN
32                  12                  14  ...                 NaN
33                   5                   5  ...                 NaN
34                  12                  12  ...                 NaN
35                   5                   6  ...                 NaN
36                   6                   5  ...                 NaN
37                   6                   6  ...                 NaN
38                   5                   5  ...                 NaN
39                   4                   5  ...                 NaN
40                 NaN                 NaN  ...                 NaN

                                                                \
0  2016-05-01 00:00:00 2016-06-01 00:00:00 2016-07-01 00:00:00
0             4.084635            7.796788                 5.9
1             0.235452            0.142691                 0.1
2             0.398069                   -                   -
3             0.636786             0.56106                 0.5
4             0.174628            0.114002                 0.1
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN
24                 NaN                 NaN                 NaN
25                 NaN                 NaN                 NaN
26                 NaN                 NaN                 NaN
27                 NaN                 NaN                 NaN
28                 NaN                 NaN                 NaN
29                 NaN                 NaN                 NaN
30                 NaN                 NaN                 NaN
31                 NaN                 NaN                 NaN
32                 NaN                 NaN                 NaN
33                 NaN                 NaN                 NaN
34                 NaN                 NaN                 NaN
35                 NaN                 NaN                 NaN
36                 NaN                 NaN                 NaN
37                 NaN                 NaN                 NaN
38                 NaN                 NaN                 NaN
39                 NaN                 NaN                 NaN
40                 NaN                 NaN                 NaN

                                                                \
0  2016-08-01 00:00:00 2016-09-01 00:00:00 2016-10-01 00:00:00
0                    -                   -                   -
1             0.124278            0.214251            0.375652
2                  1.3             0.60803             0.86753
3             0.459524            0.651359            0.930611
4             0.073921            0.171315            0.250188
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN
24                 NaN                 NaN                 NaN
25                 NaN                 NaN                 NaN
26                 NaN                 NaN                 NaN
27                 NaN                 NaN                 NaN
28                 NaN                 NaN                 NaN
29                 NaN                 NaN                 NaN
30                 NaN                 NaN                 NaN
31                 NaN                 NaN                 NaN
32                 NaN                 NaN                 NaN
33                 NaN                 NaN                 NaN
34                 NaN                 NaN                 NaN
35                 NaN                 NaN                 NaN
36                 NaN                 NaN                 NaN
37                 NaN                 NaN                 NaN
38                 NaN                 NaN                 NaN
39                 NaN                 NaN                 NaN
40                 NaN                 NaN                 NaN


0  2016-11-01 00:00:00 2016-12-01 00:00:00  Ann. Avg
0                    -                   -  2.890105
1              0.51512                 0.4  0.352968
2             1.289749                 1.4  1.496738
3             0.813291                 0.7  0.920825
4             0.126812                 0.1  0.216265
5                  NaN                 NaN       NaN
6                  NaN                 NaN       NaN
7                  NaN                 NaN       NaN
8                  NaN                 NaN       NaN
9                  NaN                 NaN       NaN
10                 NaN                 NaN       NaN
11                 NaN                 NaN       NaN
12                 NaN                 NaN       NaN
13                 NaN                 NaN       NaN
14                 NaN                 NaN       NaN
15                 NaN                 NaN       NaN
16                 NaN                 NaN       NaN
17                 NaN                 NaN       NaN
18                 NaN                 NaN       NaN
19                 NaN                 NaN       NaN
20                 NaN                 NaN       NaN
21                 NaN                 NaN       NaN
22                 NaN                 NaN       NaN
23                 NaN                 NaN       NaN
24                 NaN                 NaN       NaN
25                 NaN                 NaN       NaN
26                 NaN                 NaN       NaN
27                 NaN                 NaN       NaN
28                 NaN                 NaN       NaN
29                 NaN                 NaN       NaN
30                 NaN                 NaN       NaN
31                 NaN                 NaN       NaN
32                 NaN                 NaN       NaN
33                 NaN                 NaN       NaN
34                 NaN                 NaN       NaN
35                 NaN                 NaN       NaN
36                 NaN                 NaN       NaN
37                 NaN                 NaN       NaN
38                 NaN                 NaN       NaN
39                 NaN                 NaN       NaN
40                 NaN                 NaN       NaN

[41 rows x 112 columns]

In [655]:
data1

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,"Balanagar , CITD office",4.3,4.6,4.5,4.7,4.5,4.8,4.9,4.8,4.6,5,4.9,5.2,4.733333
1,"Uppal, Modern food Industry, IDA",4.2,4.4,4.5,4.5,4.6,4.7,5,4.8,4.6,5.4,4.9,5.8,4.783333
2,"Jubilee Hills, Police station",4.2,4.4,4.4,4.5,4.5,4.5,4.5,4.5,4.4,4.9,4.6,6.7,4.675
3,"Paradise, HMWS &SB Pump house",4.2,4.4,4.5,4.6,4.6,4.6,4.7,4.8,4.6,5,4.8,5.6,4.7
4,"Charminar, TSRTC bus station",4.2,4.5,4.5,4.6,4.5,4.7,4.8,4.6,4.6,5.1,4.6,5.8,4.708333
5,"Jeedimetla, Industrial Association building",4.3,4.5,4.4,4.6,4.6,4.8,4.8,4.8,4.6,4.9,4.8,8.9,5.0
6,"Buddha Purnima Project office, Tank Bund",4.3,4.2,4.4,4.5,4.7,4.6,4.5,4.4,4.3,4.7,4.7,4.8,4.508333
7,"MGBS, Bus stand",4.3,4.3,4.4,4.6,4.8,4.6,4.7,4.8,4.5,4.7,4.6,4.8,4.591667
8,"Chikkadapally, Lepakshi Emporium",4.2,4.1,4.5,4.5,4.7,5,4.9,4.9,4.5,5,4.7,5.3,4.691667
9,"Langar House, Police Station",4.3,4.4,4.6,4.6,4.7,4.8,4.7,4.7,4.4,4.9,4.7,4.5,4.608333
10,"Madhapur, Shilpa Kalavedika",4.3,4.2,4.3,4.5,4.7,4.9,4.5,4.5,4.3,4.5,4.5,4.7,4.491667
11,"Shameerpet, MRO office",4.3,4.2,4.3,4.5,4.6,4.4,4.5,4.5,4.4,4.3,4.4,4.6,4.416667
12,"Kukatpally, JNTU",4.3,4.2,4.5,4.6,4.6,5.2,5,4.7,4.5,5.1,5,5.6,4.775
13,"Sainikpuri, MRO office",4.3,4.2,4.4,4.3,4.7,5.1,4.5,4.7,4.3,5.2,4.4,4.3,4.533333
14,"Rajendranagar, NG Ranga Agricultural University",4.2,4.1,4.1,4.3,4.5,4.3,4.3,4.3,4.2,4.6,4.2,4.5,4.3
15,"Nacharam, Police station",4.3,4.3,4.5,4.7,4.7,4.9,4.7,5.2,4.6,5.1,4.8,5,4.733333
16,"Abids, Police station",4.3,4.2,4.4,4.6,4.8,4.7,4.7,4.8,4.4,4.8,4.7,5,4.616667
17,"KBRN Park, DFO office",4.2,4.2,4.5,4.3,4.4,4.3,4.3,4.4,4.2,4.6,4.4,4.5,4.358333
18,Sanathnagar,5.29469,4.7,6.3,9.097026,5.062038,5.270953,5,6.195295,6.812404,13.71205,30.47144,10.4,9.026325
19,HCU,13.042545,9.351498,10.7,9.1,7.07936,4.887878,4.6,4.988065,4.771528,11.81311,18.47602,9.8,9.050834
20,Zoopark,11.350935,6.196918,5.420403,6.1,5.070821,NaN,NaN,8.928455,6.854236,6.086657,13.80522,8.8,7.861364
21,Pashamylaram,23.1,12,10.572109,8.858591,5.648909,4.813937,3.7,4.301424,7.906579,21.40628,36.83995,14.1,12.770648
22,KUDA,7,7,6.7,7,8,7,7,6,8,7,7,8,7.141667
23,"Mee-Seva, Warangal",7,7,7.1,7,8,7,7,7,7,7,6,8,7.091667
24,Balasamudram,6.3,4.8,-,5.5,6.3,8,6,5.5,6.8,7.5,8,9,6.7
25,Nakkalagutta,6.8,4.5,-,6.8,6.3,8,7,5,7,7.3,8,8,6.790909
26,Godavarikhani,9,10,8.96,8,9,7,7,7,8,8,7,8,8.08
27,"DIC building, Karimnagar",8,9,7.7,7,5,5,4,6,6,6,7,7,6.475
28,"CER Club, Kothagudem",8,8,7.4,8,7,6,8,5,7,7,6,8,7.116667
29,Jalasouda,6,7,6.1,8,7,5,8,5,8,7,7,8,6.841667
30,Kothur,9,10,7.5,7,8,10,8,9,9,8,9,9,8.625
31,R.C.Puram,6,6,7,5,5,6,5,5,5,6,6,5,5.583333
32,Bollaram,10,Ins. Repair,NaN,NaN,12,14,13,12,14,13,14,10,12.444444
33,Sangareddy,5,5,5,5,5,5,5,5,5,5,5,5,5
34,PETL,13,12,14,13,11,11,12,12,12,12,9,9,11.666667
35,Gaddapotharam,5,5,6,5,5,6,6,5,6,5,5,5,5.333333
36,"Nalgonda RO, Building",7,6,6,5,6,6,6,6,5,6,6,5,5.833333
37,"Choutuppal, Nalgonda",7,7,7,7,7,6,6,6,6,7,6,5,6.416667
38,Subhasnagar/ Nizamabad,-,-,-,-,-,4,4,5,5,6,5,5,4.857143
39,Adilabad/ Mandamarri,-,-,-,-,-,4,4,4,5,5,5,5,4.571429

In [656]:
data2

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,"Balanagar , CITD office",29.2,26.3,37.7,30.8,27.1,27.9,26.1,25.8,29.2,33,36.7,43.8,31.133333
1,"Uppal, Modern food Industry, IDA",24.7,26,23.8,26.9,26.1,32.7,23.3,25.6,28.9,27.3,32.4,43.7,28.45
2,"Jubilee Hills, Police station",28.7,28.5,30.3,26.8,27.3,26.9,22.7,29.1,29.7,28.6,27.5,31.3,28.116667
3,"Paradise, HMWS &SB Pump house",31.9,25.3,28.2,29.3,28.3,28.5,20.6,30.2,30,26.9,32.1,35.3,28.883333
4,"Charminar, TSRTC bus station",32,30,33.4,33,31.1,28.5,22.3,25.6,27.5,32.5,34.3,34.2,30.366667
5,"Jeedimetla, Industrial Association building",28.6,26.1,26,26.1,29.2,30,22.7,26.9,27.3,28.3,33,31.2,27.95
6,"Buddha Purnima Project office, Tank Bund",17.4,22.1,20.1,20.8,23.3,22.1,20.6,18.1,16.9,21.7,19.6,24.6,20.608333
7,"MGBS, Bus stand",21.3,20.7,19.6,21.5,20.6,20.1,19.6,20.2,18,21.8,23,23.8,20.85
8,"Chikkadapally, Lepakshi Emporium",21.9,21.5,22.9,18.5,21,23.1,25.7,22.2,20.3,25.1,20.9,25.1,22.35
9,"Langar House, Police Station",23.1,21.7,19.9,22.4,26.6,25.1,21.8,21.4,20.7,25.4,22.8,24.4,22.941667
10,"Madhapur, Shilpa Kalavedika",20.6,19.7,19.3,19.1,22.6,18.9,17.8,18,16.7,18.4,17,19.6,18.975
11,"Shameerpet, MRO office",17.7,16.7,16.4,20,19.6,16.5,16.9,15.5,14.9,16.8,15.6,18.6,17.1
12,"Kukatpally, JNTU",22.3,22.3,24,25.2,28,25.9,22.1,23.8,24.6,25.1,33.2,41.1,26.466667
13,"Sainikpuri, MRO office",15.8,18.8,18.3,16.9,17.7,18.9,15.4,17.9,16,19.5,19.7,18.8,17.808333
14,"Rajendranaga, NG Rang Agricultural University",16.1,16.2,16.2,16.6,16.1,16.1,15,16.4,12.9,16.9,14.3,17.2,15.833333
15,"Nacharam, Police station",20.6,22.9,22.3,23.5,24.3,23.6,25,21.2,20.3,26,23.7,25.8,23.266667
16,"Abids, Police station",22.7,26.7,24.5,26.2,25.8,24.3,25,22,20.3,23.8,25.3,23.4,24.166667
17,"KBRN Park, DFO office",19.8,15.7,24,17.2,18.5,17.7,14.9,17.1,14.4,19.6,17.5,20.2,18.05
18,Punjagutta,68.793843,51.098616,66.17,75.157058,71.154023,77.925907,78.5,NaN,NaN,NaN,NaN,-,69.828492
19,Sanathnagar,67.1101,46.2,48.3,51.090372,47.392425,30.45251,25.6,24.03859,25.69912,51.16865,60.38508,45.5,43.578071
20,HCU,59.705381,54.431707,57.4,60,18.854597,11.24652,11.6,29.74674,33.41584,47.63754,65.09923,42.9,41.00313
21,Zoopark,58.755689,57.6,55.813636,49.2,52.419814,NaN,NaN,17.89061,16.50282,42.48441,64.88364,48.6,46.415062
22,Pashamylaram,82.7,62.7,55.01,56.111595,76.297074,65.92497,66.6,75.53783,64.87439,69.47612,44.70104,65.1,65.419418
23,KUDA,20,20,22.8,28,22,20,22,20,25,26,23,30,23.233333
24,"Mee-Seva, Warangal",26,19,21.8,20,19,22,20,28,20,22,22,30,22.483333
25,Balasamudram,9.8,9,-,14,11.5,14,15,9.5,14,18.2,26,28,15.363636
26,Nakkalagutta,10.3,9.5,-,16,14.5,13,17,10,15.8,19.8,29,26,16.445455
27,Godavarikhani,21,26,36,34,30,31,23,25,28,26,29,27,28
28,"DIC building, Karimnagar",22,25,32.1,29,21,19,20,20,23,23,23,26,23.591667
29,"CER Club, Kothagudem",22,20,20.7,21,19,13,24,17,31,24,23,28,21.891667
30,Jalasouda,19,19,20.7,19,19,21,22,14,17,23,24,27,20.391667
31,Kothur,28,32,29.5,26,39,34,35,35,20,31,29,28,30.541667
32,R.C.Puram,28,28,27,26,26,25,26,25,22,26,24,24,25.583333
33,Bollaram,26,Ins. Repair,NaN,NaN,24,26,24,25,24,28,26,26,25.444444
34,Sangareddy,23,23,21,23,23,22,21,22,20,24,22,23,22.25
35,PETL,21,24,25,25,23,21,24,27,23,25,24,25,23.916667
36,Gaddapotharam,27,27,27,27,26,24,25,23,22,23,23,24,24.833333
37,"Nalgonda RO, Building",27,27,26,25,27,26,26,25,24,25,26,23,25.583333
38,"Choutuppal, Nalgonda",28,28,29,28,28,28,27,28,25,27,25,25,27.166667
39,Subhasnagar/ Nizamabad,-,-,-,-,-,15,17,18,18,22,21,21,18.857143
40,Adilabad/ Mandamarri,-,-,-,-,-,15,16,17,18,22,20,21,18.428571

In [657]:
data3

,Station Name,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,"Balanagar , CITD office",184,208,124,136,114,107,96,108,87,105,152,147,130.666667
1,"Uppal, Modern food Industry, IDA",116,105,96,94,87,92,78,67,66,94,120,131,95.5
2,"Jubilee Hills, Police station",111,129,109,113,103,96,81,79,65,106,127,172,107.583333
3,"Paradise, HMWS &SB Pump house",139,146,135,141,129,119,101,105,91,104,120,117,120.583333
4,"Charminar, TSRTC bus station",134,129,109,116,100,99,85,85,71,99,143,124,107.833333
5,"Jeedimetla, Industrial Association building",172,134,133,122,111,93,75,76,73,108,151,134,115.166667
6,Buddha Purnima Project office,77,77,70,52,67,52,41,47,38,57,81,106,63.75
7,"MGBS, Bus stand",81,80,98,95,71,67,68,54,47,74,83,90,75.666667
8,"Chikkadapally, Lepakshi Emporium",90,83,93,74,66,73,63,78,62,89,100,109,81.666667
9,"Langar House, Police Station",120,125,112,86,70,68,65,64,54,75,109,116,88.666667
10,"Madhapur, Shilpa Kalavedika",97,90,89,84,70,58,55,49,40,65,101,105,75.25
11,"Shameerpet, MRO office",82,64,84,78,62,77,65,75,71,74,83,60,72.916667
12,"Kukatpally, JNTU",99,83,78,84,80,80,67,65,65,95,137,139,89.333333
13,"Sainikpuri, MRO office",85,88,85,71,78,79,66,73,62,91,80,114,81
14,"Rajendranaga, NG Rang Agricultural University",63,76,67,72,65,64,71,60,58,66,75,78,67.916667
15,"Nacharam, Police station",129,136,131,128,112,104,98,68,60,106,132,139,111.916667
16,"Abids, Police station",136,121,118,122,91,79,87,77,70,105,136,140,106.833333
17,"KBRN Park, DFO office",80,67,78,64,45,41,36,39,30,54,87,76,58.083333
18,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,NaN,NaN,NaN,NaN,-,111.460011
19,HCU,102.967742,90.965517,106,92,58.551724,36,28,31.3566,33.10981,94.40902,142.6903,80.3,74.695893
20,Zoopark,165.240592,130.689655,131.612903,115,81.184277,NaN,NaN,38.27944,35.21622,115.4603,176.5938,117,110.627719
21,Pashamylaram,104.7,92.057818,105.166667,92.794441,63.651302,49.49132,37,43.81779,62.67391,132.7546,194.0749,96,89.515229
22,KUDA,73,72,68,74,76,72,51,44,46,62,56,83,64.75
23,"Mee-Seva, Warangal",76,72,63,73,84,68,56,36,52,61,83,84,67.333333
24,Balasamudram,56,51,-,62,76,70,64,58,53,52,88,87,65.181818
25,Nakkalagutta,66,65,-,77,83,67,57,60,57,71,76,81,69.090909
26,Godavarikhani,115,93,76,74,56,41,23,41,35,58,98,106,68
27,"DIC building, Karimnagar",69,59,42,62,52,47,23,33,29,50,69,83,51.5
28,"CER Club, Kothagudem",77,71,61,63,60,49,37,45,47,60,56,66,57.666667
29,Jalasouda,46,51,54,51,47,47,41,37,39,48,55,60,48
30,Kothur,98,82,71,95,61,77,61,73,52,86,96,70,76.833333
31,R.C.Puram,98,97,93,91,61,56,48,56,47,84,97,91,76.583333
32,Bollaram,171,Ins. Repair,NaN,NaN,165,200,190,108,111,134,136,148,151.444444
33,Sangareddy,79,70,75,66,61,56,50,58,46,76,79,75,65.916667
34,PETL,97,95,97,79,70,86,74,92,60,72,84,89,82.916667
35,Gaddapotharam,97,95,90,82,58,50,44,58,42,75,88,79,71.5
36,"Nalgonda RO, Building",64,62,59,61,54,55,54,54,56,59,58,65,58.416667
37,"Choutuppal, Nalgonda",49,66,74,69,69,59,61,57,60,63,61,61,62.416667
38,Subhasnagar/ Nizamabad,67,64,66,68,71,61,57,58,56,64,60,62,62.833333
39,Adilabad/ Mandamarri,62,68,71,70,69,66,60,61,58,67,63,65,65

In [658]:
data4

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-15 00:00:00,2016-05-15 00:00:00,2016-06-15 00:00:00,2016-07-15 00:00:00,2016-08-15 00:00:00,2016-09-15 00:00:00,2016-10-15 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
1,"Balanagar , CITD office",-,-,-,-,33,49,46,43,35,43,75,71,49.375
2,"Uppal, Modern food Industry, IDA",-,-,-,-,32,38,35,28,29,45,60,70,42.125
3,"Jubilee Hills, Police station",-,-,-,-,37,37,34,33,27,37,45,69,39.875
4,"Paradise, HMWS &SB Pump house",-,-,-,-,48,42,50,48,37,50,58,73,50.75
5,"Charminar, TSRTC bus station",-,-,-,-,43,45,39,35,29,46,70,75,47.75
6,"Jeedimetla, Industrial Association Office",-,-,-,-,44,48,37,34,32,49,73,64,47.625
7,Sanathnagar,72.22408,53,61,50.857143,40.135753,29.68814,18,10.29435,19.08601,44.68506,72.96806,46.6,43.21155
8,HCU,49.451613,40.241379,41,33,21.566667,15,10,10.85432,15.01611,43.41203,76.64773,35.9,32.674154
9,Zoopark,79.149194,62.241379,59.354839,48,32,NaN,NaN,17.91037,16.81935,59.96438,103.6406,58.5,53.758011
10,Pashamylaram,54.1,45,43.6,34.099797,22.998591,17.74306,12,12.43079,23.22283,55.8727,101.9308,43.2,38.849881
11,R.C.Puram,-,-,-,-,33,34,15,28,23,28,43,33,29.625
12,Sangareddy,-,-,-,-,36,23,24,13,14,23,36,31,25
13,Gaddapotharam,-,-,-,-,35,24,23,24,19,34,41,34,29.25
14,"Nalgonda RO, Building",-,-,-,-,-,-,-,-,-,-,-,35,35
15,Subhasnagar/ Nizamabad,-,-,-,-,43,38,28,28,27,32,29,32,32.125
16,Adilabad/ Mandamarri,-,-,-,-,40,40,30,29,28,33,30,34,33

In [659]:
data4

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-15 00:00:00,2016-05-15 00:00:00,2016-06-15 00:00:00,2016-07-15 00:00:00,2016-08-15 00:00:00,2016-09-15 00:00:00,2016-10-15 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
1,"Balanagar , CITD office",-,-,-,-,33,49,46,43,35,43,75,71,49.375
2,"Uppal, Modern food Industry, IDA",-,-,-,-,32,38,35,28,29,45,60,70,42.125
3,"Jubilee Hills, Police station",-,-,-,-,37,37,34,33,27,37,45,69,39.875
4,"Paradise, HMWS &SB Pump house",-,-,-,-,48,42,50,48,37,50,58,73,50.75
5,"Charminar, TSRTC bus station",-,-,-,-,43,45,39,35,29,46,70,75,47.75
6,"Jeedimetla, Industrial Association Office",-,-,-,-,44,48,37,34,32,49,73,64,47.625
7,Sanathnagar,72.22408,53,61,50.857143,40.135753,29.68814,18,10.29435,19.08601,44.68506,72.96806,46.6,43.21155
8,HCU,49.451613,40.241379,41,33,21.566667,15,10,10.85432,15.01611,43.41203,76.64773,35.9,32.674154
9,Zoopark,79.149194,62.241379,59.354839,48,32,NaN,NaN,17.91037,16.81935,59.96438,103.6406,58.5,53.758011
10,Pashamylaram,54.1,45,43.6,34.099797,22.998591,17.74306,12,12.43079,23.22283,55.8727,101.9308,43.2,38.849881
11,R.C.Puram,-,-,-,-,33,34,15,28,23,28,43,33,29.625
12,Sangareddy,-,-,-,-,36,23,24,13,14,23,36,31,25
13,Gaddapotharam,-,-,-,-,35,24,23,24,19,34,41,34,29.25
14,"Nalgonda RO, Building",-,-,-,-,-,-,-,-,-,-,-,35,35
15,Subhasnagar/ Nizamabad,-,-,-,-,43,38,28,28,27,32,29,32,32.125
16,Adilabad/ Mandamarri,-,-,-,-,40,40,30,29,28,33,30,34,33

In [660]:
data5

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,"Balanagar , CITD office",57,71,88,82,79,79,63,67,97,65,71,83,75.166667
1,"Uppal, Modern food Industry, IDA",58,64,85,90,94,122,55,63,77,71,70,75,77
2,"Jubilee Hills, Police station",76,79,84,85,82,87,73,79,56,65,60,73,74.916667
3,"Paradise, HMWS &SB Pump house",61,47,61,75,75,75,72,75,87,65,65,71,69.083333
4,"Charminar, TSRTC bus station",75,105,83,83,105,88,73,70,64,87,63,72,80.666667
5,"Jeedimetla, Industrial Association building",149,261,148,102,123,94,67,70,95,103,79,98,115.75
6,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,-,-,-,-,-,111.460011
7,HCU,20.524323,19.33253,18,20,13.969799,10.88833,8.9,14.47275,12.20577,13.97383,25.14931,17.1,16.20972
8,Zoopark,10.458198,10.42952,10.351596,24.5,30.907149,NaN,NaN,16.53539,9.616372,15.59165,20.3662,16.8,16.555608
9,Pashamylaram,43.8,29.8,18.401793,15.833707,28.34395,11.94547,13,10.4171,17.6016,24.6967,23.27017,22,21.592541
10,KUDA,22,21,22,21,21,21,18,20,20,22,22,22,21
11,"Mee-Seva, Warangal",22,21,24,21,21,28,24,22,20,22,21,23,22.416667
12,Godavarikhani,31,29,25,25,22,23,18,21,21,21,25,22,23.583333
13,"DIC building, Karimnagar",27,24,25,21,23,21,23,21,21,25,22,24,23.083333
14,"CER Club, Kothagudem",-,-,-,-,-,20,21,21,21,21,26,21,21.571429
15,Jalasouda,-,-,-,-,-,20,22,20,21,21,28,22,22
16,Kothur,36,24,28,21,25,47,46,30,29,27,28,24,30.416667
17,R.C.Puram,21,21,21,21,21,21,21,21,21,21,21,21,21
18,Sangareddy,-,-,-,-,-,21,21,21,21,21,21,21,21
19,Gaddapotharam,-,-,-,-,-,22,21,21,21,21,21,21,21.142857
20,"Nalgonda RO, Building",21.3,21.2,21.9,21,20,21,21,21,21,21,21,21,21.033333
21,"Choutuppal, Nalgonda",27.7,26.7,26.3,27,24,25,23,23,23,22,22,21,24.225
22,Subhasnagar/ Nizamabad,-,-,-,-,-,21,21,21,21,21,21,21,21
23,Adilabad/ Mandamarri,-,-,-,-,-,21,21,21,21,21,21,21,21

In [661]:
data6

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,Punjagutta,5.814413,2.551924,4.41,3.773212,7.416257,11.224644,6.8,-,-,-,-,-,5.998636
1,HCU,27.070968,23.044828,29,32.4,25.58,24.8,10.2,12.27337,22.06474,35.47315,45.04376,34.9,26.820901
2,Zoopark,32.190325,38.9,44.338514,44.3,36.641379,NaN,NaN,10.3,20.9,31.3,39.4,28.6,32.687022
3,Sanathnagar,78.83308,73.3,76.6,73.324666,57.022625,41.3,21,20.8,25.9,52.4,83.1,67.6,55.931698
4,Pashamylaram,43.6,55.7,56.19557,52.932704,37.888175,6.156533,6.6,15.48519,19.21792,30.22503,56.72544,44.4,35.427213

In [662]:
data7

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,Punjagutta,1.900873,1.579276,1.54,1.818254,1.665658,1.680787,1.6,-,-,-,-,-,1.68355
1,HCU,0.914516,0.96069,1.04,1,0.878333,0.8,0.7,0.751629,0.835901,0.950597,0.631969,0.8,0.855303
2,Zoopark,1.143265,1.052414,0.998393,0.91,0.744483,No data,No data,0.47,0.46,0.71,0.95,1.1,0.853855
3,Sanathnagar,0.87413,0.715385,0.76,0.788929,0.712581,0.44,0.45,0.4,0.48,0.63,0.75,0.9,0.658419
4,Pashamylaram,1.493887,1.424343,0.709527,0.637408,0.509185,0.530889,0.7,0.835825,0.68689,0.877528,0.938498,1,0.861998

In [663]:
# change the coloum name station name of data3  to Sampling Location
data3 = data3.rename(columns={'Station Name': 'Sampling Location'})

In [664]:
data3

,Sampling Location,2016-01-15 00:00:00,2016-02-15 00:00:00,2016-03-15 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,Ann. Avg
0,"Balanagar , CITD office",184,208,124,136,114,107,96,108,87,105,152,147,130.666667
1,"Uppal, Modern food Industry, IDA",116,105,96,94,87,92,78,67,66,94,120,131,95.5
2,"Jubilee Hills, Police station",111,129,109,113,103,96,81,79,65,106,127,172,107.583333
3,"Paradise, HMWS &SB Pump house",139,146,135,141,129,119,101,105,91,104,120,117,120.583333
4,"Charminar, TSRTC bus station",134,129,109,116,100,99,85,85,71,99,143,124,107.833333
5,"Jeedimetla, Industrial Association building",172,134,133,122,111,93,75,76,73,108,151,134,115.166667
6,Buddha Purnima Project office,77,77,70,52,67,52,41,47,38,57,81,106,63.75
7,"MGBS, Bus stand",81,80,98,95,71,67,68,54,47,74,83,90,75.666667
8,"Chikkadapally, Lepakshi Emporium",90,83,93,74,66,73,63,78,62,89,100,109,81.666667
9,"Langar House, Police Station",120,125,112,86,70,68,65,64,54,75,109,116,88.666667
10,"Madhapur, Shilpa Kalavedika",97,90,89,84,70,58,55,49,40,65,101,105,75.25
11,"Shameerpet, MRO office",82,64,84,78,62,77,65,75,71,74,83,60,72.916667
12,"Kukatpally, JNTU",99,83,78,84,80,80,67,65,65,95,137,139,89.333333
13,"Sainikpuri, MRO office",85,88,85,71,78,79,66,73,62,91,80,114,81
14,"Rajendranaga, NG Rang Agricultural University",63,76,67,72,65,64,71,60,58,66,75,78,67.916667
15,"Nacharam, Police station",129,136,131,128,112,104,98,68,60,106,132,139,111.916667
16,"Abids, Police station",136,121,118,122,91,79,87,77,70,105,136,140,106.833333
17,"KBRN Park, DFO office",80,67,78,64,45,41,36,39,30,54,87,76,58.083333
18,Punjagutta,126,109.714378,118.89,114.169048,109.35424,107.092412,95,NaN,NaN,NaN,NaN,-,111.460011
19,HCU,102.967742,90.965517,106,92,58.551724,36,28,31.3566,33.10981,94.40902,142.6903,80.3,74.695893
20,Zoopark,165.240592,130.689655,131.612903,115,81.184277,NaN,NaN,38.27944,35.21622,115.4603,176.5938,117,110.627719
21,Pashamylaram,104.7,92.057818,105.166667,92.794441,63.651302,49.49132,37,43.81779,62.67391,132.7546,194.0749,96,89.515229
22,KUDA,73,72,68,74,76,72,51,44,46,62,56,83,64.75
23,"Mee-Seva, Warangal",76,72,63,73,84,68,56,36,52,61,83,84,67.333333
24,Balasamudram,56,51,-,62,76,70,64,58,53,52,88,87,65.181818
25,Nakkalagutta,66,65,-,77,83,67,57,60,57,71,76,81,69.090909
26,Godavarikhani,115,93,76,74,56,41,23,41,35,58,98,106,68
27,"DIC building, Karimnagar",69,59,42,62,52,47,23,33,29,50,69,83,51.5
28,"CER Club, Kothagudem",77,71,61,63,60,49,37,45,47,60,56,66,57.666667
29,Jalasouda,46,51,54,51,47,47,41,37,39,48,55,60,48
30,Kothur,98,82,71,95,61,77,61,73,52,86,96,70,76.833333
31,R.C.Puram,98,97,93,91,61,56,48,56,47,84,97,91,76.583333
32,Bollaram,171,Ins. Repair,NaN,NaN,165,200,190,108,111,134,136,148,151.444444
33,Sangareddy,79,70,75,66,61,56,50,58,46,76,79,75,65.916667
34,PETL,97,95,97,79,70,86,74,92,60,72,84,89,82.916667
35,Gaddapotharam,97,95,90,82,58,50,44,58,42,75,88,79,71.5
36,"Nalgonda RO, Building",64,62,59,61,54,55,54,54,56,59,58,65,58.416667
37,"Choutuppal, Nalgonda",49,66,74,69,69,59,61,57,60,63,61,61,62.416667
38,Subhasnagar/ Nizamabad,67,64,66,68,71,61,57,58,56,64,60,62,62.833333
39,Adilabad/ Mandamarri,62,68,71,70,69,66,60,61,58,67,63,65,65

In [665]:
# merge data on sampling location without dropping any row
data_list =  [data1, data2, data3, data4, data5, data6, data7, data8]
data= data_list[0]
for i in range(1, len(data_list)):
    data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')

C:\Users\Rahs\AppData\Local\Temp\ipykernel_17424\4165807397.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2016-03-15 00:00:00_x', '2016-12-01 00:00:00_x', '2016-02-15 00:00:00_x', 'Ann. Avg_x', '2016-11-01 00:00:00_x', '2016-01-15 00:00:00_x'} in the result is deprecated and will raise a MergeError in a future version.
  data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')
C:\Users\Rahs\AppData\Local\Temp\ipykernel_17424\4165807397.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2016-04-01 00:00:00_x', '2016-07-01 00:00:00_x', '2016-10-01 00:00:00_x', '2016-06-01 00:00:00_x', '2016-08-01 00:00:00_x', '2016-05-01 00:00:00_x', '2016-09-01 00:00:00_x'} in the result is deprecated and will raise a MergeError in a future version.
  data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')
C:\Users\Rahs\AppData\Local\Temp\ipykernel_17424\4165807397.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2016-03-15 00:00:00_x', '2016-12-01 00:00:00_x', '2016-02-15 00:00:00_x', 'Ann. Avg_x', '2016-11-01 00:00:00_x', '2016-01-15 00:00:00_x'} in the result is deprecated and will raise a MergeError in a future version.
  data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')
C:\Users\Rahs\AppData\Local\Temp\ipykernel_17424\4165807397.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2016-04-01 00:00:00_x', '2016-07-01 00:00:00_x', '2016-10-01 00:00:00_x', '2016-06-01 00:00:00_x', '2016-08-01 00:00:00_x', '2016-05-01 00:00:00_x', '2016-09-01 00:00:00_x'} in the result is deprecated and will raise a MergeError in a future version.
  data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')
C:\Users\Rahs\AppData\Local\Temp\ipykernel_17424\4165807397.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2016-03-15 00:00:00_x', '2016-12-01 00:00:00_x', '2016-02-15 00:00:00_x', 'Ann. Avg_x', '2016-11-01 00:00:00_x', '2016-01-15 00:00:00_x'} in the result is deprecated and will raise a MergeError in a future version.
  data = pd.merge(data, data_list[i], on='Sampling Location', how='outer')

In [667]:
data

,Sampling Location,2016-01-15 00:00:00_x,2016-02-15 00:00:00_x,2016-03-15 00:00:00_x,2016-04-01 00:00:00_x,2016-05-01 00:00:00_x,2016-06-01 00:00:00_x,2016-07-01 00:00:00_x,2016-08-01 00:00:00_x,2016-09-01 00:00:00_x,...,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00_y,2016-12-01 00:00:00_y,Ann. Avg_y
0,"Balanagar , CITD office",4.3,4.6,4.5,4.7,4.5,4.8,4.9,4.8,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Uppal, Modern food Industry, IDA",4.2,4.4,4.5,4.5,4.6,4.7,5,4.8,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Jubilee Hills, Police station",4.2,4.4,4.4,4.5,4.5,4.5,4.5,4.5,4.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Paradise, HMWS &SB Pump house",4.2,4.4,4.5,4.6,4.6,4.6,4.7,4.8,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Charminar, TSRTC bus station",4.2,4.5,4.5,4.6,4.5,4.7,4.8,4.6,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"Jeedimetla, Industrial Association building",4.3,4.5,4.4,4.6,4.6,4.8,4.8,4.8,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Buddha Purnima Project office, Tank Bund",4.3,4.2,4.4,4.5,4.7,4.6,4.5,4.4,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"MGBS, Bus stand",4.3,4.3,4.4,4.6,4.8,4.6,4.7,4.8,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Chikkadapally, Lepakshi Emporium",4.2,4.1,4.5,4.5,4.7,5,4.9,4.9,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"Langar House, Police Station",4.3,4.4,4.6,4.6,4.7,4.8,4.7,4.7,4.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Madhapur, Shilpa Kalavedika",4.3,4.2,4.3,4.5,4.7,4.9,4.5,4.5,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Shameerpet, MRO office",4.3,4.2,4.3,4.5,4.6,4.4,4.5,4.5,4.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"Kukatpally, JNTU",4.3,4.2,4.5,4.6,4.6,5.2,5,4.7,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"Sainikpuri, MRO office",4.3,4.2,4.4,4.3,4.7,5.1,4.5,4.7,4.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Rajendranagar, NG Ranga Agricultural University",4.2,4.1,4.1,4.3,4.5,4.3,4.3,4.3,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"Nacharam, Police station",4.3,4.3,4.5,4.7,4.7,4.9,4.7,5.2,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"Abids, Police station",4.3,4.2,4.4,4.6,4.8,4.7,4.7,4.8,4.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"KBRN Park, DFO office",4.2,4.2,4.5,4.3,4.4,4.3,4.3,4.4,4.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Sanathnagar,5.29469,4.7,6.3,9.097026,5.062038,5.270953,5,6.195295,6.812404,...,1.125023,0.636786,0.56106,0.5,0.459524,0.651359,0.930611,0.813291,0.7,0.920825
19,HCU,13.042545,9.351498,10.7,9.1,7.07936,4.887878,4.6,4.988065,4.771528,...,0.4,0.235452,0.142691,0.1,0.124278,0.214251,0.375652,0.51512,0.4,0.352968
20,Zoopark,11.350935,6.196918,5.420403,6.1,5.070821,NaN,NaN,8.928455,6.854236,...,1.1,0.398069,-,-,1.3,0.60803,0.86753,1.289749,1.4,1.496738
21,Pashamylaram,23.1,12,10.572109,8.858591,5.648909,4.813937,3.7,4.301424,7.906579,...,0.427885,0.174628,0.114002,0.1,0.073921,0.171315,0.250188,0.126812,0.1,0.216265
22,KUDA,7,7,6.7,7,8,7,7,6,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Mee-Seva, Warangal",7,7,7.1,7,8,7,7,7,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Balasamudram,6.3,4.8,-,5.5,6.3,8,6,5.5,6.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Nakkalagutta,6.8,4.5,-,6.8,6.3,8,7,5,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Godavarikhani,9,10,8.96,8,9,7,7,7,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"DIC building, Karimnagar",8,9,7.7,7,5,5,4,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"CER Club, Kothagudem",8,8,7.4,8,7,6,8,5,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Jalasouda,6,7,6.1,8,7,5,8,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Kothur,9,10,7.5,7,8,10,8,9,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,R.C.Puram,6,6,7,5,5,6,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Bollaram,10,Ins. Repair,NaN,NaN,12,14,13,12,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Sangareddy,5,5,5,5,5,5,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,PETL,13,12,14,13,11,11,12,12,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Gaddapotharam,5,5,6,5,5,6,6,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"Nalgonda RO, Building",7,6,6,5,6,6,6,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"Choutuppal, Nalgonda",7,7,7,7,7,6,6,6,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Subhasnagar/ Nizamabad,-,-,-,-,-,4,4,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Adilabad/ Mandamarri,-,-,-,-,-,4,4,4,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"Rajendranaga, NG Rang Agricultural University",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Punjagutta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.325061,4.084635,7.796788,5.9,-,-,-,-,-,2.890105
42,Buddha Purnima Project office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,"Mee-Seva, Warangal",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"DIC building, Karimnagar",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,"Paradise, HMWS &SB Pump house",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,"Jeedimetla, Industrial Association Office",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Subhasnagar/ Nizamabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Adilabad/ Mandamarri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Subhasnagar/ Nizamabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [670]:
data.to_csv('clean AAQ Data 2016.csv')